"""empty message

Revision ID: 3cfec9130c05
Revises: 5a189612fcd1
Create Date: 2025-03-11 16:19:27.929001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfec9130c05'
down_revision = '5a189612fcd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_blitz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_blitz', schema=None) as batch_op:
        batch_op.drop_column('word_correct')

    # ### end Alembic commands ###
